"""Finished linking and implementing all 4 tables. Time for testing.

Revision ID: 0778d0dc71f2
Revises: c2060f850288
Create Date: 2025-05-13 15:26:26.633725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0778d0dc71f2'
down_revision: Union[str, None] = 'c2060f850288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('positions_ibfk_2', 'positions', type_='foreignkey')
    op.drop_column('positions', 'worker_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('worker_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('positions_ibfk_2', 'positions', 'workers', ['worker_id'], ['worker_id'])
    # ### end Alembic commands ###
