"""Full rebuilt schema, after droping old tables due to lots of structural changes, and alembic not registering them

Revision ID: ebb29441a3ee
Revises: 0778d0dc71f2
Create Date: 2025-05-13 15:40:15.200104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb29441a3ee'
down_revision: Union[str, None] = '0778d0dc71f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('works_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('workers')
    op.drop_table('companies')
    # ### end Alembic commands ###
